Add wikipedia source prototype
republicofdata-io/social_signals pull request #4
Opened 2023-11-27 15:01 UTC by enzoMagalhaes

# Description

Created a Wikipedia source prototype that extracts data from articles on Wikipedia. The WikipediaSource class includes methods for searching Wikipedia, retrieving data for a single Wikipedia page, and fetching data from multiple related Wikipedia pages. The data is stored in a DataFrame with specified columns.

searching example:
![image](https://github.com/republicofdata-io/social_signals/assets/88254468/c6b3c99c-085d-4b8b-b566-6dd2c42d072e)

fetching a single page example:
![image](https://github.com/republicofdata-io/social_signals/assets/88254468/1a9fee26-4b96-4b81-8223-e77b289e220b)

fetching multiple pages related to a search term example:
![image](https://github.com/republicofdata-io/social_signals/assets/88254468/17c10ed1-0c5d-4f67-8c27-4899fa206654)

# Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

No unit tests were made. The functionality has been tested using the following steps:

- Create an instance of the WikipediaSource class.
- Perform a Wikipedia search for a specific term and print the search results.
- Retrieve data from a single Wikipedia page and print the fetched data.
- Fetch data from multiple related Wikipedia pages and print the overall data.

## Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

- [x] Execute wikipedia_example.py
- [x] Confirm search results are obtained.
- [x] Verify data is correctly fetched from both a single page and multiple related pages.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-11-27 15:48 UTC, olivierdupuis requested changes
I changed the branch to merge into. I want us to merge into a `dev` branch, not a `release` branch as those are already released.

This is a great PR. PR template was completed perfectly. And agree with you, structuring around a class is more elegant. I'll eventually refactor GDELT to follow that convention.

I see that you haven't added unit tests. It's probably a good call. I didn't feel like it added a whole lot of benefits to my own dev. Just having a good enough example is good. 

One small thing to change. Can you add a link to your wikipedia_example on the main examples page: https://github.com/enzoMagalhaes/social_signals/blob/wikipedia_source/examples/index.md

Besides that, it looks good. Good job :) Once you make that small change, request another review from me and I'll approve.

Btw, when you open a PR, you need to add me as a reviewer for me to get notified. Also, once I approve, you will be the one that merge the branch into the dev branch. I want the branch author to be responsible for the merge at the end.

2023-12-04 12:54 UTC, olivierdupuis commented on pyproject.toml
> +pandas = "2.1.3"
Can you change it back to 1.5.3. There are compatibility issues with version 2+.

2023-12-10 18:35 UTC, enzoMagalhaes commented on pyproject.toml
> +pandas = "2.1.3"
Just downgraded the pandas version back to 1.5.3 :+1:

2023-12-10 22:44 UTC, olivierdupuis approved these changes
Looks good @enzoMagalhaes 👍  You can merge!

2023-12-11 13:14 UTC, merged