X source
republicofdata-io/social_signals pull request #5
Opened 2023-12-04 21:05 UTC by olivierdupuis

# Description

New nodule to source X data. This module allows you to search [recent tweets](https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-recent. 

# Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

- [ ] Unit tests at `tests/test_x.py` ran successfully
- [ ] Ran `examples/x_example.py` successfully

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-12-10 22:44 UTC, enzoMagalhaes requested changes
I wrote some suggestions for small changes to the XSource class and unit tests. The source looks good to me! I think that we should improve the unit tests and have a github actions yml that tests and publishes the package on pypi

2023-12-10 22:44 UTC, enzoMagalhaes commented on examples/x_example.py
I just wasnt able to run the example using a free tier account :disappointed: ,  don't know if that's  expected though. Anyway, since this is a open source library i think that it would be nice to have a brief explanation on how to properly connect the XSource to twitter API.

the error I was facing: 

"When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal." 

NOTE: i was using a bearer token of an app already attached to a project

There is an issue about this problem, but its probably just me being dumb :monkey_face:  
https://github.com/twitterdev/Twitter-API-v2-sample-code/issues/58

2023-12-10 22:44 UTC, enzoMagalhaes commented on pyproject.toml
> +tweepy = "^4.14.0"
I see that you have added this dependency but it doesn't seem to be used anywhere.

2023-12-10 22:44 UTC, enzoMagalhaes commented on social_signals/x/source.py
> +        search_url = "https://api.twitter.com/2/tweets/search/recent"
this variable could be a class constant just like TWEET_COLUMNS

2023-12-10 22:44 UTC, enzoMagalhaes commented on social_signals/x/source.py
> +        print(response.status_code)
remove print

2023-12-10 22:44 UTC, enzoMagalhaes commented on tests/test_x.py
I think that the tests could cover things like data types and asserting that the format is what we expect. The search test is not really fetching any data from source. Not sure if that's on purpose, but it kind of misses the point of doing unit tests to me

2023-12-10 22:44 UTC, enzoMagalhaes commented on tests/__pycache__/__init__.cpython-39.pyc
__pycache__ should be excluded by gitignore, but it doesn't

2023-12-12 21:03 UTC, olivierdupuis commented on dist/social_signals-0.0.2-py3-none-any.whl
None, I'll add it.

2023-12-12 21:10 UTC, olivierdupuis commented on examples/x_example.py
This is using the API version 2 and it requires a Basic tier account.
https://developer.twitter.com/en/docs/twitter-api/tweets/search/introduction

I'll add something to that effect in the documentation.

2023-12-12 21:10 UTC, olivierdupuis commented
> I wrote some suggestions for small changes to the XSource class and unit tests. The source looks good to me! I think that we should improve the unit tests and have a github actions yml that tests and publishes the package on pypi

@enzoMagalhaes Can you add an issue in this repo to keep track of this?

2023-12-12 21:16 UTC, olivierdupuis commented on pyproject.toml
> +tweepy = "^4.14.0"
True, I experimented with it and then decided against it. Will remove. Good catch 👍

2023-12-12 21:21 UTC, olivierdupuis commented on tests/test_x.py
yeah, not sure what the right balance is here. This data is being a paid API access. So we can't really unit test without introducing a real bearer key. I think we should have a discussion on the whole unit testing strategy. Want to set up a call for that?

2023-12-14 18:01 UTC, enzoMagalhaes commented on tests/test_x.py
I think that it would be nice to discuss about what tests should be implemented. As for the API credentials, we could just pass the bearer key as an env variable (or github secrets if you want to build actions for testing).

2023-12-14 18:40 UTC, enzoMagalhaes approved these changes
I cant test the api on my local machine, but by just looking at it, I have nothing to add. Approved!

2023-12-14 22:00 UTC, merged